//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IonicAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetParent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetParent()
        {
            this.CriteriaRatings = new HashSet<CriteriaRating>();
            this.Meetings = new HashSet<Meeting>();
            this.Pets1 = new HashSet<Pet>();
            this.PetServiceInstructions = new HashSet<PetServiceInstruction>();
            this.PotentialSitters = new HashSet<PotentialSitter>();
            this.Ratings = new HashSet<Rating>();
            this.ServicePets = new HashSet<ServicePet>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.SitterComplaints = new HashSet<SitterComplaint>();
            this.SystemUsers = new HashSet<SystemUser>();
        }
    
        public int PetParentID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<decimal> PhoneNr { get; set; }
        public string ParentAddress { get; set; }
        public string ParentPassword { get; set; }
        public string Pets { get; set; }
        public Nullable<int> SuburbID { get; set; }
        public Nullable<int> DiscoveryTypeID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
    
        public virtual CIty CIty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriteriaRating> CriteriaRatings { get; set; }
        public virtual DiscoveryType DiscoveryType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meetings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pet> Pets1 { get; set; }
        public virtual Province Province { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual Title Title { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PetServiceInstruction> PetServiceInstructions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotentialSitter> PotentialSitters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicePet> ServicePets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitterComplaint> SitterComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
    }
}
