//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IonicAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PetSitter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PetSitter()
        {
            this.ContactNoes = new HashSet<ContactNo>();
            this.CriteriaRatings = new HashSet<CriteriaRating>();
            this.Doucments = new HashSet<Doucment>();
            this.Meetings = new HashSet<Meeting>();
            this.PotentialSitters = new HashSet<PotentialSitter>();
            this.Ratings = new HashSet<Rating>();
            this.SitterComplaints = new HashSet<SitterComplaint>();
            this.SitterReferences = new HashSet<SitterReference>();
            this.Students = new HashSet<Student>();
            this.SystemUsers = new HashSet<SystemUser>();
        }
    
        public int PetSitterID { get; set; }
        public string PetSitterName { get; set; }
        public string PetSitterSurname { get; set; }
        public string PetSitterEmailAddress { get; set; }
        public string SitterPassword { get; set; }
        public Nullable<decimal> PetSitterPhoneNum { get; set; }
        public string PetSitterAddress { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public string Reference { get; set; }
        public byte[] Picture { get; set; }
        public string About { get; set; }
        public string Area { get; set; }
        public Nullable<int> SitterStatusID { get; set; }
        public Nullable<int> TertiaryID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public Nullable<int> SuburbID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
    
        public virtual CIty CIty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactNo> ContactNoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriteriaRating> CriteriaRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doucment> Doucments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meeting> Meetings { get; set; }
        public virtual Province Province { get; set; }
        public virtual PetSitterStatu PetSitterStatu { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual TertiaryEducation TertiaryEducation { get; set; }
        public virtual UserRole UserRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PotentialSitter> PotentialSitters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitterComplaint> SitterComplaints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SitterReference> SitterReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Students { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
    }
}
